### ISSUE TITLE
pr0gram crawler broken?

### ISSUE THREAD

**Issue by jkowalleck** [k4cg/nichtparasoup#79]
tested the pr0gram crawler today, seams to be broken.
can someone confirm?

before rewriting it, wait for my go. i am currently writing some convenience methods for the crawlers ;-)

**Comment by faheus** [comment]
didn't saw pr0gramm posts in a long time either. if i only activate pr0, the cache stays pretty empty. 
i dunno the exact way how you get pictures out of pr0.
In my eyes it is obsolete, as of most pictures are posted on soup or reddit before they get into pr0. 
But its not bad to have the crawler.

**Comment by noqqe** [comment]
I think there is some confusion about `static` `top` and `new`.

Config specifys all of them as subsites, which is incorrect.

``` ini 
Pr0gramm: static ,new, top
```

Only `new` and `top` are subsites to crawl. `static` i used because the default view of Pr0gramm is a minified and uncrawlable mess of javascript. So static represents same contents in better crawlable page source.

Urls to crawl:

http://pr0gramm.com/static/new/
http://pr0gramm.com/static/top/

Already working on fixing it. Lets see how far i can get.
